Class GrenThrower : Weapon {

	default {
		Radius 20;
		Height 16;
		Weapon.SelectionOrder 2500;
		+WEAPON.NOAUTOFIRE
		+WEAPON.NOAUTOAIM
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 999;
		Weapon.AmmoType "RocketAmmo";
		//Weapon.Kickback 100;
		Weapon.SlotNumber 5;
		Inventory.PickupMessage "Grabbed some Grenades.";	
	}

	States {
		Spawn:
			LAUN A -1;
			Stop;
		Ready:
			MISG A 1 A_WeaponReady();
			Loop;
		Deselect:
			MISG A 1 A_Lower();
			Loop;
		Select: 
			MISG A 1 A_Raise();
			Loop;
		Fire: 
			MISG B 8 A_GunFlash();
			MISG B 12 A_FireProjectile("GrenTearThrown",0,1,0,0,0,-1);
			MISG B 0 A_ReFire();
			Goto Ready;
		Flash: 
			MISF A 3 bright A_Light1();
			MISF B 4 bright;
			MISF C 4 bright A_Light2();
			MISF D 4 bright A_Light2();
			Goto LightDone;
	}	
}


Class GrenFragThrown : Grenade {
	
	bool logDeath, logGrenade, logDetonate, logMushroom, logAll;

	override void PostBeginPlay() {
		logAll = true;
		super.PostBeginPlay();
	}
	
	default {
		Radius 4;
        Height 4;
        Speed 55;
        Scale 0.35;
        DamageFunction (random(20,30));
        BounceType "Doom";
        //BounceSound "grenade/bounce";
        BounceFactor 0.35;
        WallBounceFactor 0.75;
        Gravity 0.15;
        ReactionTime 85;
        Species "Grenade";
        DamageType "Explosive";
        Projectile;
        +THRUGHOST
        +THRUSPECIES
        +BOUNCEONWALLS
        +BOUNCEONFLOORS
        +BOUNCEONCEILINGS
        +ALLOWBOUNCEONACTORS
        -NOGRAVITY
        +DONTGIB
        +MOVEWITHSECTOR
        +EXTREMEDEATH
        +ROLLCENTER
        +ROLLSPRITE
        +USEBOUNCESTATE
        +CANBOUNCEWATER
        +DONTBLAST
        +DONTTHRUST
		Obituary "Once you've pulled the pin on Mr. Grenade, he is no longer your friend, %o.";
	}
	
	States {
		Spawn:
			SGRN A 1 Bright;
			Loop;
		Death:
			MISL B 8 Bright {
				if (logAll) {
					Console.printf("projectile went to death state");
				}
				A_Explode();
			}
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
 		// this all never happens, for some fucked up reason.
		/*
		Grenade:
			MISL A 100 { 
				if (logAll) {
					Console.printf("projectile went to grenade state");
				}
				resolveState("Death");
			}
			Wait;
		Detonate:
			MISL B 4 {
				if (logAll) {
					Console.printf("projectile went to detonate state");
				}
				A_Scream();
			}
			MISL C 6 A_Detonate();
			MISL D 10;
			Stop;
		Mushroom:
			MISL B 8 {
				if (logAll) {
					Console.printf("projectile went to mushroom state");
				}
				A_Mushroom();
			}
			Goto Death+1;
			*/
	}
}

Class GrenTearThrown: GrenFragThrown {
		
	default {
		DamageFunction (0);
		DamageType "None";
	}
	
	override void PostBeginPlay() {
		logAll = true;
		super.PostBeginPlay();
	}
	
	States {
		Spawn:
			SGRN A 1 Bright;
			Loop;
		Death:
			MISL B 8 Bright {
				if (logAll) {
					Console.printf("projectile went to death state");
				}
				//A_Explode();
				A_SpawnItemEx("tearGasCloud", random(-2,2), random(-2,2), random(1,3), random(-2,2), random(-2,2), 0);
				A_SpawnItemEx("tearGasCloud", random(-2,2), random(-2,2), random(1,3), random(-2,2), random(-2,2), 0);
				A_SpawnItemEx("tearGasCloud", random(-2,2), random(-2,2), random(1,3), random(-2,2), random(-2,2), 0);
				A_SpawnItemEx("tearGasCloud", random(-2,2), random(-2,2), random(1,3), random(-2,2), random(-2,2), 0);
			}
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
	
	
}


Class tearGasCloud : Actor {

	int stateCount;
	int cloudRadius;
	
	property GasDuration: stateCount;
	property cloudRadius: cloudRadius;
	
	default {
		tearGasCloud.cloudRadius 64;
		tearGasCloud.GasDuration 4;
		Radius 32;
		Height 64;
		Mass 0x7fffffff;
		+NOBLOCKMAP
		+NOGRAVITY
		+DROPOFF
		+NODAMAGETHRUST
		+DONTSPLASH
		+FLOAT
		FloatSpeed 10;
		//PoisonDamage 10, 10, 35;
		//+FOILINVUL
		//+CANBLAST
		//+BLOODLESSIMPACT
		//+BLOCKEDBYSOLIDACTORS
		RenderStyle "Translucent";
		Alpha 0.4;
		//DeathSound "PoisonShroomDeath";
		//DamageType TearGas;
	}	
	States {
		Spawn:
			GTXM A 1;
			GTXM A 1 A_Scream();
			GTXM ABCDE 10 A_Explode(1, invoker.cloudRadius, XF_HURTSOURCE, false, invoker.cloudRadius);
			goto CloudLoop;
		CloudLoop:
			GTXM ABCD 10 A_Explode(1, invoker.cloudRadius, XF_HURTSOURCE, false, invoker.cloudRadius);
			GTXM E 10 {
				A_Explode(1, invoker.cloudRadius, XF_HURTSOURCE, false, invoker.cloudRadius);
				if (invoker.stateCount > 0) {
					invoker.stateCount--;
					return resolveState("CloudLoop");
					}
				else return resolveState("Death");
			}
		Death:
			GTXS ABCDE 7 {
				A_Explode(1, invoker.cloudRadius, XF_HURTSOURCE, false, invoker.cloudRadius);
				A_FadeOut(0.1);
			}
			Stop;
	}
}